### PR TITLE
Fix for Spells & Abilities

### PR DESCRIPTION
**Pull request by funkworkz**
Fix for "Spells & Abilities" post May 2015

Please test before releasing

### CODE REVIEW

**Comment by alphaONE2** [comment]
Um... something weird about these changes... the diffs are showing nearly every line has changed... did you change the line endings?

**Comment by z16** [comment]
That was my first thought upon seeing that. It makes it a bit harder to compare the actual changes, but wouldn't stop me from merging this, as file endings in POLUtils is all over the place anyway.

One thing that bothers me a little is that I cannot find corresponding changes to [ResourceExtractor](/Windower/ResourceExtractor), which is odd. All I found was commit Windower/ResourceExtractor@ebee79429effd3c92a09110b05e6ccb877e0ca5e that expanded the *range* of items parsed as armor, to account for new additions to the game, but nothing in our parsing algorithm itself broke. I will check out POLUtils (including this pull request) later today.

**Comment by funkworkz** [comment]
It was probably an encoding issue...

**Comment by z16** [comment]
Sorry, I'm a noob when it comes to POLUtils. Where exactly can I find this section, "Spells & Abilities Info"? I can only find "Abilities" and "Spells" under the "String Tables" menu in the data browser, and they both seem to work fine.

**Comment by funkworkz** [comment]
String Tables > Common > Spells & Abilities

**Comment by z16** [comment]
I'm gonna close this request, as it turns out there was more wrong than just that, and your code also introduced some new possible bugs. I refactored the file completely to use part ResourceExtractor's code, as that is more stable for changes to the DAT file it tries to parse. But thanks for pointing out what was wrong.

**Pull request closed without merging**
